#!/bin/bash

VALUE=`xclip -o`;

echo "VALUE: $VALUE";

if [[ $VALUE == meet.google.com* ]]; then
  google-chrome-stable --app=https://$VALUE;
  exit 0;
fi

if [[ $VALUE == http* ]]; then
  google-chrome-stable --app=$VALUE;
  exit 0;
fi

if [[ $VALUE == file:* ]]; then
  google-chrome-stable --app=$VALUE;
  exit 0;
fi
